---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Load and execute roles
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - mamono210.aws_bootstrap
        - mamono210.aws_s3_get
