---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check if PosgreSQL is installed
      ansible.builtin.command: psql --version
      register: psql_version
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show PostgreSQL version
      ansible.builtin.debug:
        var: psql_version

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
